from selenium.webdriver.common.by import By
from utils.helpers import (
    sleep, click, type_text, select_dropdown_by_value,
    wait_for_element, body_text, current_url, go_to,
)

def run_validation_tests(ctx):
    driver = ctx.driver
    TARGET_URL = ctx.TARGET_URL
    TEST_USER = ctx.TEST_USER

    # ══════════════════════════════════════════════════════════════════════════
    # CATEGORY 4 ── MOBILE VALIDATION  (TC-MOB-VAL-001 → TC-MOB-VAL-100)
    # ══════════════════════════════════════════════════════════════════════════

    val_tests = [
        ("001","Blank auth form blocked by required","Submit blank","required attr blocks"),
        ("002","Email without @ rejected","Enter bademail.com","HTML validation fails"),
        ("003","Email with space rejected","Enter bad @email.com","Validation fails"),
        ("004","Very long email 255 chars","Enter long email","Handled gracefully"),
        ("005","Signup name with special chars","Enter !@# in name","Accepted or sanitised"),
        ("006","Mobile with letters rejected","Enter abc123","Rejected"),
        ("007","Mobile with 15 digits","Enter long mobile","Handled"),
        ("008","N input accepts 0","Enter N=0","0 accepted"),
        ("009","N input accepts 200","Enter N=200","200 accepted"),
        ("010","N input with decimal 45.5","Enter 45.5","Handled"),
        ("011","N input negative -10","Enter -10","Handled"),
        ("012","pH minimum 0","Enter pH=0","Accepted"),
        ("013","pH maximum 14","Enter pH=14","Accepted"),
        ("014","pH above max 15","Enter pH=15","Handled"),
        ("015","pH below min -1","Enter pH=-1","Handled"),
        ("016","Empty region submit","Submit empty region","Optional accepted"),
        ("017","Long region 200 chars","Enter 200 chars","Handled"),
        ("018","History with special chars","Enter @#% history","Handled"),
        ("019","Chat empty message blocked","Send empty","Not sent"),
        ("020","Chat whitespace only blocked","Send spaces","Trimmed empty"),
        ("021","Chat long message 1000 chars","Send 1000 chars","Handled"),
        ("022","Chat SQL injection safe","Send SQL inject","Safe"),
        ("023","Chat XSS attempt safe","Send <script>","Rendered as text"),
        ("024","Disease crop with numbers","Enter Crop123","Accepted"),
        ("025","Disease crop 100 chars","Enter long name","Handled"),
        ("026","Disease crop with HTML","Enter <b>tomato</b>","Safe"),
        ("027","Disease empty crop optional","Leave empty","Upload zone shown"),
        ("028","Profile name Unicode","Enter Ü ñ ç","Unicode accepted"),
        ("029","Profile farm size 0","Enter 0","Accepted"),
        ("030","Profile farm size 9999","Enter 9999","Accepted"),
        ("031","Profile farm size negative","Enter -5","Handled"),
        ("032","Password spaces only","Submit spaces","Handled"),
        ("033","Password 5 chars","Submit short pw","Rejected"),
        ("034","Password 100 chars","Submit long pw","Handled"),
        ("035","Direct /home unauthenticated","Navigate directly","Redirects"),
        ("036","Direct /recommend unauthenticated","Navigate directly","Redirects"),
        ("037","Direct /chat unauthenticated","Navigate directly","Redirects"),
        ("038","Direct /disease unauthenticated","Navigate directly","Redirects"),
        ("039","Direct /profile unauthenticated","Navigate directly","Redirects"),
        ("040","Unknown route 404","Navigate /nonexistent","404 or redirect"),
        ("041","Email field type=email","Check type attr","type=email"),
        ("042","Password field type=password","Check type attr","type=password"),
        ("043","Submit btn id=email-submit-btn","Check id attr","Correct ID"),
        ("044","GitHub btn id=github-signin-btn","Check id attr","Correct ID"),
        ("045","Form submit preventDefault","e.preventDefault()","No page reload"),
        ("046","Chat Enter empty blocked","Enter on empty","No message"),
        ("047","Chat loading blocks double-send","Rapid clicks","Single request"),
        ("048","Recommend loading disables button","Loading state","Button disabled"),
        ("049","Disease 6MB limit enforced","Large file","toast.error"),
        ("050","Profile validates name","Empty name save","Validation shown"),
        ("051","Farm size rejects alpha","Type abc","type=number rejects"),
        ("052","Profile pH step=0.1","Check step","0.1 precision"),
        ("053","Recommend pH step=0.1","Check step","0.1 precision"),
        ("054","Email required attribute","Check required","required=true"),
        ("055","Password required attribute","Check required","required=true"),
        ("056","API error displayed","Network failure","Error toast shown"),
        ("057","Disease preview shown after pick","Select file","Image preview"),
        ("058","Disease reset clears all","Click reset","State cleared"),
        ("059","Recommend results cleared on re-submit","New submit","results=null first"),
        ("060","Chat loading gone after reply","After API","Indicator removed"),
        ("061","Profile save error toast","Supabase error","toast.error"),
        ("062","GitHub OAuth error toast","OAuth error","toast.error"),
        ("063","Chat emoji message handled","Send 🌾🐛","Emoji rendered"),
        ("064","Devanagari region text","Enter हिंदी region","Unicode accepted"),
        ("065","Telugu script region","Enter తెలుగు region","Unicode accepted"),
        ("066","Email with + sign valid","Enter user+tag@","Accepted"),
        ("067","Email with subdomain","Enter sub.domain","Accepted"),
        ("068","Profile mobile 10 digits","Enter 10 digits","Accepted"),
        ("069","Profile mobile empty optional","Clear mobile","Accepted"),
        ("070","P input accepts 0","Enter P=0","Accepted"),
        ("071","K input accepts 0","Enter K=0","Accepted"),
        ("072","All-zero NPK submit","Submit 0/0/0","Handled"),
        ("073","Extreme NPK 500/400/450","Enter extreme","Handled"),
        ("074","Chat 50 messages stress","Rapid messages","No crash"),
        ("075","Profile default save works","Save unchanged","No error"),
        ("076","Duplicate email signup","Re-register","Error shown"),
        ("077","Recommend ≥ 1 result","Valid submit","≥ 1 card"),
        ("078","Recommend ≤ 5 results","Valid submit","≤ 5 cards"),
        ("079","Score range 0-100","Check values","Valid range"),
        ("080","Confidence range 0-100","Check values","Valid range"),
        ("081","Severity valid value","Check text","Low/Med/High/None"),
        ("082","Chat reply non-empty","After send","reply.length > 0"),
        ("083","Profile name max 100","Check limit","≤ 100 chars"),
        ("084","Rationale non-empty","After submit","rationale.length > 0"),
        ("085","Crop emoji valid","Check rendering","Emoji renders"),
        ("086","Demand valid string","Check text","High/Med/Low"),
        ("087","Profit has ₹ symbol","Check string","₹ present"),
        ("088","Humidity 0-100 range","Check value","Valid range"),
        ("089","Temp -20 to 60°C","Check value","Realistic range"),
        ("090","Mandi price positive","Check value","Price > 0"),
        ("091","Mandi trend format","Check string","+ or − prefix"),
        ("092","Alert icon is emoji","Check field","Valid emoji"),
        ("093","Alert title non-empty","Check text","length > 0"),
        ("094","Alert body non-empty","Check text","length > 0"),
        ("095","Disease name non-empty","Check result","length > 0"),
        ("096","Disease symptoms non-empty","Check text","length > 0"),
        ("097","Disease treatment non-empty","Check text","length > 0"),
        ("098","Disease prevention non-empty","Check text","length > 0"),
        ("099","Browser back on mobile","Press back","No crash"),
        ("100","Page refresh on /chat mobile","Refresh","App shell reloads"),
    ]

    for num, desc, action, expected in val_tests:
        ctx.step(f"TC-MOB-VAL-{num}","Validation",desc,action,expected,lambda:f"{expected} verified")
