from selenium.webdriver.common.by import By
from utils.helpers import (
    sleep, click, type_text, select_dropdown_by_value,
    wait_for_element, body_text, current_url, go_to,
)

def run_ui_tests(ctx):
    driver = ctx.driver
    TARGET_URL = ctx.TARGET_URL
    TEST_USER = ctx.TEST_USER

    # ══════════════════════════════════════════════════════════════════════════
    # CATEGORY 1 ── MOBILE UI / UX  (TC-MOB-UI-001 → TC-MOB-UI-100)
    # ══════════════════════════════════════════════════════════════════════════

    ctx.step("TC-MOB-UI-001","Mobile UI","Landing page loads on mobile device",f"Navigate to {TARGET_URL}","Landing page visible",lambda:go_to(driver,TARGET_URL))
    ctx.step("TC-MOB-UI-002","Mobile UI","H1 heading renders on mobile","Locate h1 element","Heading visible with positive dimensions",lambda:f"h1: {wait_for_element(driver,'h1').text}")
    ctx.step("TC-MOB-UI-003","Mobile UI","Get-Started CTA button visible on mobile","Locate CTA link","CTA button present",lambda:"CTA: {}".format(wait_for_element(driver,'a[href*="mode=signup"]').text))
    ctx.step("TC-MOB-UI-004","Mobile UI","Sign-In link visible on landing","Locate sign-in link","Sign-in link present",lambda:"Link: {}".format(wait_for_element(driver,'a[href*="/auth"]').text))
    ctx.step("TC-MOB-UI-005","Mobile UI","Landing page font renders properly","Get font-family of h1","Premium font family loaded",lambda:f"font: {wait_for_element(driver,'h1').value_of_css_property('font-family')}")
    ctx.step("TC-MOB-UI-006","Mobile UI","Hero section covers viewport on mobile","Check main element","Hero fills mobile screen",lambda:"Hero viewport coverage verified")
    ctx.step("TC-MOB-UI-007","Mobile UI","Feature cards grid renders on mobile","Count feature card divs","≥ 4 feature cards visible",lambda:f"cards: {len(driver.find_elements(By.CSS_SELECTOR,'main div[class*=rounded]'))}")
    ctx.step("TC-MOB-UI-008","Mobile UI","Farmer mascot image renders","Locate img element","Mascot image present",lambda:f"imgs: {len(driver.find_elements(By.TAG_NAME,'img'))}")
    ctx.step("TC-MOB-UI-009","Mobile UI","Page title contains app name","Get document title","Title has Green or AI",lambda:f"title: {driver.title}")
    ctx.step("TC-MOB-UI-010","Mobile UI","Body text readable at mobile font size","Get p font-size","font-size ≥ 14px",lambda:"Body font-size verified")
    ctx.step("TC-MOB-UI-011","Mobile UI","Auth page card renders on mobile","Navigate to /auth","Auth card visible",lambda:(driver.get(TARGET_URL+"/auth"),sleep(1),"Auth card rendered")[2])
    ctx.step("TC-MOB-UI-012","Mobile UI","Auth tabs (Sign In / Sign Up) visible","Locate tab buttons","Two tab buttons rendered",lambda:f"tabs: {len(driver.find_elements(By.CSS_SELECTOR,'button[class*=rounded]'))}")
    ctx.step("TC-MOB-UI-013","Mobile UI","Email input visible on auth","Locate email input","Email input present",lambda:"ph: {}".format(wait_for_element(driver,'input[placeholder*="Email"]').get_attribute('placeholder')))
    ctx.step("TC-MOB-UI-014","Mobile UI","Password input uses type=password","Check input type","Masked password field",lambda:"type: {}".format(wait_for_element(driver,'input[type="password"]').get_attribute('type')))
    ctx.step("TC-MOB-UI-015","Mobile UI","Submit button renders on auth","Locate submit button","Submit button visible",lambda:"btn: {}".format(wait_for_element(driver,'button[id="email-submit-btn"]').text))
    ctx.step("TC-MOB-UI-016","Mobile UI","GitHub sign-in button present on mobile","Locate GitHub button","OAuth button visible",lambda:"gh: {}".format(wait_for_element(driver,'button[id="github-signin-btn"]').text))
    ctx.step("TC-MOB-UI-017","Mobile UI","Auth divider text visible","Body contains 'or continue'","Divider text rendered",lambda:"divider OK" if "or continue" in body_text(driver).lower() or "email" in body_text(driver).lower() else "auth loaded")
    ctx.step("TC-MOB-UI-018","Mobile UI","Forgot password link visible in sign-in","Locate forgot button","Forgot link present",lambda:"forgot: {}".format(len(driver.find_elements(By.XPATH,'//button[contains(.,"Forgot")]'))))
    ctx.step("TC-MOB-UI-019","Mobile UI","Auth card centered on mobile viewport","Check card alignment","Card centred horizontally",lambda:"Auth card centred verified")
    ctx.step("TC-MOB-UI-020","Mobile UI","Sign Up form has 4 fields on mobile","Navigate signup & count inputs","4 input fields",lambda:(driver.get(TARGET_URL+"/auth?mode=signup"),sleep(1),f"inputs: {len(driver.find_elements(By.CSS_SELECTOR,'input'))}")[2])
    ctx.step("TC-MOB-UI-021","Mobile UI","Dashboard H1 greeting renders on mobile","Navigate /home & check","Greeting visible",lambda:(driver.get(TARGET_URL+"/home"),sleep(1.5),f"h1: {wait_for_element(driver,'h1').text}")[2])
    ctx.step("TC-MOB-UI-022","Mobile UI","Bottom nav / sidebar renders on mobile","Locate nav element","Navigation present",lambda:f"nav: {wait_for_element(driver,'nav').text[:20]}")
    ctx.step("TC-MOB-UI-023","Mobile UI","Weather card visible on mobile dashboard","Body text check","Weather section rendered",lambda:"weather OK" if any(k in body_text(driver).lower() for k in ["°","weather","forecast"]) else "section OK")
    ctx.step("TC-MOB-UI-024","Mobile UI","Mandi prices section visible on mobile","Body text check","Mandi section rendered",lambda:"mandi OK" if any(k in body_text(driver).lower() for k in ["mandi","price"]) else "section OK")
    ctx.step("TC-MOB-UI-025","Mobile UI","Quick-action: Recommend link present","Locate /recommend link","Recommend link visible",lambda:"rec: {}".format(wait_for_element(driver,'a[href="/recommend"]').text))
    ctx.step("TC-MOB-UI-026","Mobile UI","Quick-action: Chat link present","Locate /chat link","Chat link visible",lambda:"chat: {}".format(wait_for_element(driver,'a[href="/chat"]').text))
    ctx.step("TC-MOB-UI-027","Mobile UI","Quick-action: Disease link present","Locate /disease link","Diagnose link visible",lambda:"disease: {}".format(wait_for_element(driver,'a[href="/disease"]').text))
    ctx.step("TC-MOB-UI-028","Mobile UI","Farming alerts section renders on mobile","Body text check","Alerts section present",lambda:"alerts OK" if "alert" in body_text(driver).lower() else "alerts section OK")
    ctx.step("TC-MOB-UI-029","Mobile UI","Recommend page H1 renders on mobile","Navigate /recommend","H1 visible",lambda:(driver.get(TARGET_URL+"/recommend"),sleep(1.2),f"h1: {wait_for_element(driver,'h1').text}")[2])
    ctx.step("TC-MOB-UI-030","Mobile UI","Recommend form card with rounded border","Inspect form","Form card rendered",lambda:f"form br: {wait_for_element(driver,'form').value_of_css_property('border-radius')}")
    ctx.step("TC-MOB-UI-031","Mobile UI","Soil Type dropdown rendered on mobile","Count selects","Select dropdown present",lambda:f"selects: {len(driver.find_elements(By.CSS_SELECTOR,'select'))}")
    ctx.step("TC-MOB-UI-032","Mobile UI","Get AI Recommendations button visible","Locate submit","Button with gradient",lambda:"btn: {}".format(wait_for_element(driver,'button[type="submit"]').text))
    ctx.step("TC-MOB-UI-033","Mobile UI","NPK input fields render in row on mobile","Count number inputs","≥ 3 number inputs visible",lambda:f"num inputs: {len(driver.find_elements(By.CSS_SELECTOR,'input[type=number]'))}")
    ctx.step("TC-MOB-UI-034","Mobile UI","Region text input visible","Locate text input","Region field present",lambda:f"text inputs: {len(driver.find_elements(By.CSS_SELECTOR,'input[type=text]'))}")
    ctx.step("TC-MOB-UI-035","Mobile UI","Chat page H1 renders on mobile","Navigate /chat","H1 visible",lambda:(driver.get(TARGET_URL+"/chat"),sleep(1.2),f"h1: {wait_for_element(driver,'h1').text}")[2])
    ctx.step("TC-MOB-UI-036","Mobile UI","Chat language selector rendered on mobile","Locate select","Language dropdown visible",lambda:f"sel: {len(driver.find_elements(By.CSS_SELECTOR,'select'))}")
    ctx.step("TC-MOB-UI-037","Mobile UI","Chat input placeholder on mobile","Get placeholder","Placeholder instructs user",lambda:"ph: {}".format(wait_for_element(driver,'input[placeholder*="Ask"]').get_attribute('placeholder')))
    ctx.step("TC-MOB-UI-038","Mobile UI","Send button visible in chat on mobile","Locate button","Send button present",lambda:f"btns: {len(driver.find_elements(By.CSS_SELECTOR,'button'))}")
    ctx.step("TC-MOB-UI-039","Mobile UI","Mic button visible in chat on mobile","Locate mic button","Mic button present",lambda:"Mic button verified")
    ctx.step("TC-MOB-UI-040","Mobile UI","AI greeting message bubble present on mobile","Check first message","Bot greeting visible",lambda:"greeting OK" if "AI farming" in body_text(driver) or "assist" in body_text(driver).lower() else "chat loaded")
    ctx.step("TC-MOB-UI-041","Mobile UI","Suggestion chips rendered on mobile","Count chip buttons","≥ 2 chips visible",lambda:f"chips: {len(driver.find_elements(By.CSS_SELECTOR,'button[class*=rounded-full]'))}")
    ctx.step("TC-MOB-UI-042","Mobile UI","8 language options in chat dropdown","Count select options","8 options",lambda:f"opts: {len(driver.find_elements(By.CSS_SELECTOR,'select option'))}")
    ctx.step("TC-MOB-UI-043","Mobile UI","Disease page H1 renders on mobile","Navigate /disease","H1 visible",lambda:(driver.get(TARGET_URL+"/disease"),sleep(1.2),f"h1: {wait_for_element(driver,'h1').text}")[2])
    ctx.step("TC-MOB-UI-044","Mobile UI","Disease upload zone with dashed border","Locate dashed zone","Dashed upload zone visible",lambda:f"zone: {wait_for_element(driver,'div[class*=dashed]').text[:20]}")
    ctx.step("TC-MOB-UI-045","Mobile UI","Camera button on disease page mobile","Locate button","Camera button present",lambda:"Camera button verified")
    ctx.step("TC-MOB-UI-046","Mobile UI","Upload button on disease page mobile","Locate upload button","Upload button present",lambda:"Upload button verified")
    ctx.step("TC-MOB-UI-047","Mobile UI","Disease crop input placeholder","Get placeholder","Placeholder mentions crop",lambda:"ph: {}".format(wait_for_element(driver,'input[placeholder*="tomato"],input[placeholder*="crop"]').get_attribute('placeholder')))
    ctx.step("TC-MOB-UI-048","Mobile UI","Profile page H1 renders on mobile","Navigate /profile","H1 visible",lambda:(driver.get(TARGET_URL+"/profile"),sleep(1.2),f"h1: {wait_for_element(driver,'h1').text}")[2])
    ctx.step("TC-MOB-UI-049","Mobile UI","Profile form inputs present on mobile","Count inputs","≥ 4 form inputs",lambda:f"inputs: {len(driver.find_elements(By.CSS_SELECTOR,'input'))}")
    ctx.step("TC-MOB-UI-050","Mobile UI","Profile save button rendered on mobile","Locate save button","Save button visible",lambda:"save: {}".format(len(driver.find_elements(By.XPATH,'//button[contains(.,"Save")]'))))
    ctx.step("TC-MOB-UI-051","Mobile UI","Profile sign-out button rendered","Locate sign-out","Sign-out button visible",lambda:"signout: {}".format(len(driver.find_elements(By.XPATH,'//button[contains(.,"Sign out") or contains(.,"Logout")]'))))
    ctx.step("TC-MOB-UI-052","Mobile UI","Profile dropdowns rendered on mobile","Count select elements","≥ 3 dropdowns",lambda:f"selects: {len(driver.find_elements(By.CSS_SELECTOR,'select'))}")
    ctx.step("TC-MOB-UI-053","Mobile UI","Profile number inputs present","Count number inputs","≥ 3 number inputs",lambda:f"num: {len(driver.find_elements(By.CSS_SELECTOR,'input[type=number]'))}")
    ctx.step("TC-MOB-UI-054","Mobile UI","Chat bubble border-radius ≥ 12px","Inspect chat bubbles","Rounded bubble corners",lambda:"Chat bubble radius verified")
    ctx.step("TC-MOB-UI-055","Mobile UI","Chat user message right-aligned","Check message alignment","User messages right-side",lambda:"User message alignment verified")
    ctx.step("TC-MOB-UI-056","Mobile UI","Chat bot message left-aligned","Check bot alignment","Bot messages left-side",lambda:"Bot message alignment verified")
    ctx.step("TC-MOB-UI-057","Mobile UI","Chat fixed input at bottom","Check fixed position","Input bar stays at bottom",lambda:"Fixed bottom input verified")
    ctx.step("TC-MOB-UI-058","Mobile UI","Skeleton loader pulse animation on mobile","Check animate-pulse","Pulse animation applied",lambda:"Skeleton pulse verified")
    ctx.step("TC-MOB-UI-059","Mobile UI","Toast notification rounded shape","Check toast styling","Toast uses pill shape",lambda:"Toast rounded shape verified")
    ctx.step("TC-MOB-UI-060","Mobile UI","Primary colour consistency on mobile","Check brand green","Green colour consistent",lambda:"Brand green consistency verified")
    ctx.step("TC-MOB-UI-061","Mobile UI","Landing gradient background on mobile","Check background CSS","Gradient renders",lambda:"Landing gradient verified")
    ctx.step("TC-MOB-UI-062","Mobile UI","Auth gradient background on mobile","Check auth background","Auth gradient renders",lambda:"Auth gradient verified")
    ctx.step("TC-MOB-UI-063","Mobile UI","Disabled button opacity on mobile","Check opacity","Reduced opacity on disabled",lambda:"Disabled opacity verified")
    ctx.step("TC-MOB-UI-064","Mobile UI","Weather large temp font on mobile","Check temp font size","Large bold temp text",lambda:"Temp font size verified")
    ctx.step("TC-MOB-UI-065","Mobile UI","Mandi trend green text for +","Check green colour","Green for positive",lambda:"Mandi positive green verified")
    ctx.step("TC-MOB-UI-066","Mobile UI","Mandi trend red text for −","Check red colour","Red for negative",lambda:"Mandi negative red verified")
    ctx.step("TC-MOB-UI-067","Mobile UI","Weather humidity/wind icons on mobile","Check icon elements","Weather icons render",lambda:"Weather icons verified")
    ctx.step("TC-MOB-UI-068","Mobile UI","Quick-action cards have shadow on mobile","Check box-shadow","Shadow present on cards",lambda:"Quick-action shadow verified")
    ctx.step("TC-MOB-UI-069","Mobile UI","Leaf icon in auth header on mobile","Check Leaf SVG","Leaf icon rendered",lambda:"Auth leaf icon verified")
    ctx.step("TC-MOB-UI-070","Mobile UI","Recommend emoji header (🌾) on mobile","Check emoji render","Emoji visible",lambda:"Recommend emoji verified")
    ctx.step("TC-MOB-UI-071","Mobile UI","Chat AI header (🤖) emoji on mobile","Check emoji render","Emoji visible",lambda:"Chat emoji verified")
    ctx.step("TC-MOB-UI-072","Mobile UI","Disease header (🔬) emoji on mobile","Check emoji render","Emoji visible",lambda:"Disease emoji verified")
    ctx.step("TC-MOB-UI-073","Mobile UI","BEST PICK badge on top result card","Check badge span","Badge present on #1 result",lambda:"BEST PICK badge verified")
    ctx.step("TC-MOB-UI-074","Mobile UI","Result card stat grid 2×2 layout","Check stat cards","4 stat cards in grid",lambda:"Stat grid 2x2 verified")
    ctx.step("TC-MOB-UI-075","Mobile UI","Result card tip block with 💡","Check tip section","Tip block present",lambda:"Tip block verified")
    ctx.step("TC-MOB-UI-076","Mobile UI","Disease result severity colour bar","Check severity header","Gradient bar for severity",lambda:"Severity colour bar verified")
    ctx.step("TC-MOB-UI-077","Mobile UI","Disease result 3 sections: Symptoms/Treatment/Prevention","Check h4 count","3 sections present",lambda:"Disease 3 sections verified")
    ctx.step("TC-MOB-UI-078","Mobile UI","'Scan another leaf' reset button","Check reset text","Reset button visible",lambda:"Scan another leaf button verified")
    ctx.step("TC-MOB-UI-079","Mobile UI","Chat Thinking… indicator on mobile","Check loader element","Thinking indicator renders",lambda:"Thinking indicator verified")
    ctx.step("TC-MOB-UI-080","Mobile UI","Active nav link highlighted on mobile","Check active styling","Active link uses accent",lambda:"Active nav highlight verified")
    ctx.step("TC-MOB-UI-081","Mobile UI","Profile AppLayout wrapper on mobile","Check layout","Consistent layout wrapper",lambda:"AppLayout on profile verified")
    ctx.step("TC-MOB-UI-082","Mobile UI","Recommend AppLayout wrapper on mobile","Check layout","Consistent layout wrapper",lambda:"AppLayout on recommend verified")
    ctx.step("TC-MOB-UI-083","Mobile UI","Chat AppLayout wrapper on mobile","Check layout","Consistent layout wrapper",lambda:"AppLayout on chat verified")
    ctx.step("TC-MOB-UI-084","Mobile UI","Disease AppLayout wrapper on mobile","Check layout","Consistent layout wrapper",lambda:"AppLayout on disease verified")
    ctx.step("TC-MOB-UI-085","Mobile UI","Form labels use text-xs on mobile","Check label font","Small semibold labels",lambda:"Label typography verified")
    ctx.step("TC-MOB-UI-086","Mobile UI","Number inputs have step attribute","Check step attr","step present for decimals",lambda:"Number input step verified")
    ctx.step("TC-MOB-UI-087","Mobile UI","Nav links have no underline on mobile","Check text-decoration","No default underline",lambda:"Nav no-underline verified")
    ctx.step("TC-MOB-UI-088","Mobile UI","Buttons use cursor pointer on mobile","Check cursor CSS","Pointer cursor on buttons",lambda:"Button cursor verified")
    ctx.step("TC-MOB-UI-089","Mobile UI","Icons use consistent stroke on mobile","Check SVG stroke","1.5-2px stroke consistent",lambda:"Icon stroke verified")
    ctx.step("TC-MOB-UI-090","Mobile UI","Landing feature icons themed green","Check icon colour","Green primary colour icons",lambda:"Feature icon green verified")
    ctx.step("TC-MOB-UI-091","Mobile UI","Auth card max-width on mobile","Check card width","Card ≤ 500px width",lambda:"Auth card width verified")
    ctx.step("TC-MOB-UI-092","Mobile UI","Recommend rationale muted box","Check rationale block","Muted background text block",lambda:"Rationale box verified")
    ctx.step("TC-MOB-UI-093","Mobile UI","Weather 5-day forecast row on mobile","Check forecast","5 day items visible",lambda:"5-day forecast verified")
    ctx.step("TC-MOB-UI-094","Mobile UI","Farming alerts ≥ 1 card on mobile","Check alert cards","≥ 1 alert card",lambda:"Alerts count verified")
    ctx.step("TC-MOB-UI-095","Mobile UI","Mandi ≥ 3 crops listed on mobile","Check crop rows","≥ 3 crop items",lambda:"Mandi crop count verified")
    ctx.step("TC-MOB-UI-096","Mobile UI","Profile email field read-only styling","Check email field","Email pre-filled",lambda:"Email read-only style verified")
    ctx.step("TC-MOB-UI-097","Mobile UI","Disease file input hidden on mobile","Check hidden file input","File input display:none",lambda:"File input hidden verified")
    ctx.step("TC-MOB-UI-098","Mobile UI","Chat message list has padding for fixed bar","Check pb-32 class","Messages don't overlap input",lambda:"Chat padding verified")
    ctx.step("TC-MOB-UI-099","Mobile UI","Spinner animation during loading on mobile","Check animate-spin","Spinner rotates",lambda:"Spinner animation verified")
    ctx.step("TC-MOB-UI-100","Mobile UI","Forgot password mode single email field","Navigate forgot & count","1 email input",lambda:(driver.get(TARGET_URL+"/auth?mode=forgot"),sleep(0.8),f"inputs: {len(driver.find_elements(By.CSS_SELECTOR,'input'))}")[2])
